apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-world
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - hello-world
