apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-world
roleRef:
  kind: Role
  name: hello-world
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hello-world
  namespace: $(NAMESPACE)
